### ISSUE TITLE
Put photosensitivity warning before install instructions

### ISSUE THREAD

**Issue by slacksystem** [Saltssaumure/synthesis-discord-theme#9]
Hi as someone who is photosensitive I appreciate the warning about the flickering effect, but the fact that it's below the customization options meant in my case it came too late. Fortunately, since my photosensitivity does not come from epilepsy, I will be fine (with a minor headache that will pass soon), but it would be quite helpful, especially to those with epilepsy for whom it can be quite dangerous, to make the warning visible in the readme prior to the install instructions, as many times people won't read to the end before installing something.

**Comment by Saltssaumure** [comment]
I'm very sorry to hear what happened!

By default when the theme is first installed through any of the means described in the README, the flicker *should not* be active, and should only appear if the theme file is specifically edited to enable the effect. I've tested with a fresh install of the theme to check that it behaves as I described above, and it seems to be correct based on my testing. Additional info on the following will really help me figure out what happened so that this issue does not affect any more people:

1. Are you on a current or older version of the theme?
2. Which install method did you use?
3. Have you customised the theme, and if so what method did you use?

**Comment by slacksystem** [comment]
Hi I'm not sure what I did wrong the first time because I just tried it again today so that I could give more details to you but it worked great and there was no figure so I'm pretty happy with that. Still couldn't hurt to have the warning a bit earlier in my opinion but I'm all set at this point
